### ISSUE TITLE
Redis client dies when it attempts a retry.

### ISSUE THREAD

**Issue by greim** [ortoo/node-redis-sentinel#37]
As far as I can tell, this module uses the redis client's constructor instead of the factory function, so some internal setup gets missed and things break.

The problem is reported and described in more depth here: https://github.com/mranney/node_redis/issues/735 ...but it definitely affects users of this module.

**Comment by aphorise** [comment]
I can also confirm that there are issues with this module crashing clients during reconnection / re-switch.

I've done a mock to demo:
https://github.com/aphorise/redis-sentinel-sim

In my case I get unrelated  ```toString()``` error on an ```undefined```

Are there any patch or fix?

**Comment by aphorise** [comment]
Here is the related trace when the crash occures
```
/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:158
                    throw callback_err;
                          ^
TypeError: Cannot call method 'toString' of undefined
    at Command.callback (/home/mehdi/git/redis-sentinel-sim/index.js:64:47)
    at RedisClient.flush_and_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:155:29)
    at RedisClient.on_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:191:10)
    at Socket.<anonymous> (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
```

I can also confirm that the last ```event``` prior to this occuring is: ```error```, ```reconnecting```. This issue may perhaps be more related to exceptions / emits in ```redis``` npm.

**Comment by aphorise** [comment]
After some debugging of my own code for causes I came across:
https://github.com/mranney/node_redis/issues/744
Seems as thought the aforementioned exception occurs when trying to many ```.set```  ```.get``` while no redis server maybe be in reach / connected.
